// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05ja3O-1dDHRXNzO1vAkYRewrBOBproQ',
    appId: '1:697767876930:web:cd8bb06367399b90a850db',
    messagingSenderId: '697767876930',
    projectId: 'curiosifywebui',
    authDomain: 'curiosifywebui.firebaseapp.com',
    storageBucket: 'curiosifywebui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxw_iMLw59fLV9oIjhoMs5edMH5cRUfVo',
    appId: '1:697767876930:android:00d558694c7bda66a850db',
    messagingSenderId: '697767876930',
    projectId: 'curiosifywebui',
    storageBucket: 'curiosifywebui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEhDJ89g-wdDCs4xR6CVJnd94XCaJ-5M',
    appId: '1:697767876930:ios:9c1c7c8988f93dbfa850db',
    messagingSenderId: '697767876930',
    projectId: 'curiosifywebui',
    storageBucket: 'curiosifywebui.appspot.com',
    iosBundleId: 'com.example.curiosifyUiAssignment',
  );
}
